image: docker:stable

services:
  - docker:dind

before_script:
    - git submodule update --init --recursive

build:
  stage: build
  script:
        - docker build -t zklaim-test .
        - docker run zklaim-test

